vich_uploader:
    db_driver: orm

    mappings:
        designs:
            uri_prefix: /images/designs
            upload_destination: '%kernel.project_dir%/public/images/designs'
           
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        refined:
            uri_prefix: /images/designs/refined
            upload_destination: '%kernel.project_dir%/public/images/designs/refined'
           
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        printed:
            uri_prefix: /images/designs/printed
            upload_destination: '%kernel.project_dir%/public/images/designs/printed'
           
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
