vich_uploader:
    db_driver: orm

    mappings:
        designs:
            uri_prefix: /images/designs
            upload_destination: '%kernel.project_dir%/public/images/designs'
           
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
